### ISSUE TITLE
Failed to parse XSD : getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by dalidovski** [charto/fast-xml#16]
# npm version
4.4.1

# node.js version
v6.10.1

# OS
Windows 8.1

# Issue Description
I'm trying to parse the folowing XSD file using **npm run cxsd test.xsd** : 

> <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"   
>            xmlns:tns="http://tempuri.org/PurchaseOrderSchema.xsd"   
>            targetNamespace="http://tempuri.org/PurchaseOrderSchema.xsd"   
>            elementFormDefault="qualified">  
>  <xsd:element name="PurchaseOrder" type="tns:PurchaseOrderType"/>  
>  <xsd:complexType name="PurchaseOrderType">  
>   <xsd:sequence>  
>    <xsd:element name="ShipTo" type="tns:USAddress" maxOccurs="2"/>  
>    <xsd:element name="BillTo" type="tns:USAddress"/>  
>   </xsd:sequence>  
>   <xsd:attribute name="OrderDate" type="xsd:date"/>  
>  </xsd:complexType>  
>   
>  <xsd:complexType name="USAddress">  
>   <xsd:sequence>  
>    <xsd:element name="name"   type="xsd:string"/>  
>    <xsd:element name="street" type="xsd:string"/>  
>    <xsd:element name="city"   type="xsd:string"/>  
>    <xsd:element name="state"  type="xsd:string"/>  
>    <xsd:element name="zip"    type="xsd:integer"/>  
>   </xsd:sequence>  
>   <xsd:attribute name="country" type="xsd:NMTOKEN" fixed="US"/>  
>  </xsd:complexType>  
> </xsd:schema>

However, I'm getting the folowing error:

**Error: getaddrinfo ENOTFOUND null null:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)**

**Comment by dalidovski** [comment]
After investigation, I found that I have to put an address not the filename. For example:
npm run cxsd http://localhost:80/schemas/test.xsd
