### ISSUE TITLE
Failed to parse xsd

### ISSUE THREAD

**Issue by klokoy** [charto/fast-xml#23]
When I try to parse the following xsd:

```
https://github.com/BuildingSMART/BCF-XML/blob/release_2_1/Schemas/visinfo.xsd
```

cxsd fails with the following stack:

```
TypeError: Cannot read property 'id' of undefined
    at ContextBase.copyNamespace (/Users/klokoy/projects/bcf/node_modules/cxml/dist/xml/ContextBase.js:33:49)
    at Object.exportNamespace (/Users/klokoy/projects/bcf/node_modules/cxsd/dist/xsd/Exporter.js:142:32)
    at /Users/klokoy/projects/bcf/node_modules/cxsd/dist/cli.js:40:35
    at tryCatcher (/Users/klokoy/projects/bcf/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/klokoy/projects/bcf/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/klokoy/projects/bcf/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/klokoy/projects/bcf/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/klokoy/projects/bcf/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/klokoy/projects/bcf/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/klokoy/projects/bcf/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/klokoy/projects/bcf/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

Is there a good way to figure out if the problem is with cxsd or the xsd itself?

**Comment by adamvoss** [comment]
Another failure:

```
https://maven.apache.org/plugins/maven-changes-plugin/xsd/changes-1.0.0.xsd
```

```
$ ./node_modules/.bin/cxsd changes-1.0.0.xsd
SHOULD RETRY
C:\node_modules\cget\dist\cget\Cache.js:195
            throw (err);
            ^

Error: getaddrinfo ENOTFOUND null null:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

```
$ node --version
v8.9.3
```

Microsoft Windows [Version 10.0.15063]
