### ISSUE TITLE
Cannot read property 'getScope' of undefined - Adding targetNamespace does not fix

### ISSUE THREAD

**Issue by craigsimko** [charto/fast-xml#28]
Hello, I'm trying to use cxsd but am receiving two errors that I'm not sure how to fix. I am getting the following errors:
`TypeError: Cannot read property 'getScope' of undefined`
`TypeError: Cannot read property 'id' of undefined`

I am experiencing the same error as the person in this issue:
https://github.com/charto/cxsd/issues/8

However adding "targetNamespace" did not fix my issue as it did for him.

Here is my XSD:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://some/awesome/schema">
	<xs:element name="REQUEST">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LOGIN">
					<xs:complexType>
						<xs:choice>
							<xs:element name="API_TOKEN">
								<xs:annotation>
									<xs:documentation>Used to authenticate a request as vendor sees fit.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="USER">
								<xs:complexType>
									<xs:attribute name="user_name" type="xs:string" use="required"/>
									<xs:attribute name="password" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="lender_code" use="required">
							<xs:annotation>
								<xs:documentation>Used to identify lender on LPQ system.</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="TESTFI_Lender1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="CURRENT_USER">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="USERLOGIN">
								<xs:simpleType>
									<xs:restriction base="xs:string"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="NAME">
								<xs:simpleType>
									<xs:restriction base="xs:string"/>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ACTION">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NEW_TRANSACTION">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="APP_DATA" minOccurs="0">
											<xs:annotation>
												<xs:documentation>App data can contain CLF Data, and/or a dictionary.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="CLF_DATA" minOccurs="0">
														<xs:complexType mixed="true">
															<xs:attribute name="encoding" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:enumeration value="base64"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
													<xs:element name="DICTIONARY" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Can be used for simple app data in place of CLF, or additional meta data.</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element name="FIELD" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="key" type="xs:string" use="required"/>
																		<xs:attribute name="value" type="xs:string" use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="template" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:enumeration value="ASG"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="EXISTING_TRANSACTION">
								<xs:annotation>
									<xs:documentation>For asynchronous processing, will help identify prior transaction to check upon for completion.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="transaction_id" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Depending on context, this should be default to be same as lpq_transaction_id.   However, this can be different if needed by vendor to send vendor's transaction id which may differe from lpq transactiion id.  In such case, vendor will need to provide transcation id information in the response and require custom parsing on LPQ side.</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="service_type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="GET_QUOTE"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="1.0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="lpq_transaction_id" use="required">
				<xs:annotation>
					<xs:documentation>LPQ transaction id that was passed over on first request.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="32"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>
```

**Comment by zzynx** [comment]
I experience exactly the same problem.
Any idea when this will get fixed?

**Comment by theomessin** [comment]
Same problem. Any update?

**Comment by moltar** [comment]
Same here:

```
> xsd-exp@1.0.0 cxsd ~/xsd-exp
> cxsd "https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Inventory.xsd"

TypeError: Cannot read property 'getScope' of undefined
    at Schema.init (~/xsd-exp/node_modules/cxsd/dist/xsd/types/Schema.js:32:50)
    at Parser.startElement (~/xsd-exp/node_modules/cxsd/dist/xsd/Parser.js:72:21)
    at Parser.<anonymous> (~/xsd-exp/node_modules/cxsd/dist/xsd/Parser.js:112:31)
    at Parser.emit (events.js:189:13)
    at Parser.parse (~/xsd-exp/node_modules/node-expat/lib/node-expat.js:23:22)
    at PassThrough.<anonymous> (~/xsd-exp/node_modules/cxsd/dist/xsd/Parser.js:147:17)
    at PassThrough.emit (events.js:189:13)
    at PassThrough.Readable.read (_stream_readable.js:487:10)
    at flow (_stream_readable.js:953:34)
    at resume_ (_stream_readable.js:934:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Stack:
TypeError: Cannot read property 'getScope' of undefined
    at Schema.init (~/xsd-exp/node_modules/cxsd/dist/xsd/types/Schema.js:32:50)
    at Parser.startElement (~/xsd-exp/node_modules/cxsd/dist/xsd/Parser.js:72:21)
    at Parser.<anonymous> (~/xsd-exp/node_modules/cxsd/dist/xsd/Parser.js:112:31)
    at Parser.emit (events.js:189:13)
    at Parser.parse (~/xsd-exp/node_modules/node-expat/lib/node-expat.js:23:22)
    at PassThrough.<anonymous> (~/xsd-exp/node_modules/cxsd/dist/xsd/Parser.js:147:17)
    at PassThrough.emit (events.js:189:13)
    at PassThrough.Readable.read (_stream_readable.js:487:10)
    at flow (_stream_readable.js:953:34)
    at resume_ (_stream_readable.js:934:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
TypeError: Cannot read property 'id' of undefined
    at ContextBase.copyNamespace (~/xsd-exp/node_modules/cxml/dist/xml/ContextBase.js:33:50)
    at Object.exportNamespace (~/xsd-exp/node_modules/cxsd/dist/xsd/Exporter.js:142:32)
    at ~/xsd-exp/node_modules/cxsd/dist/cli.js:40:35
    at tryCatcher (~/xsd-exp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (~/xsd-exp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (~/xsd-exp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (~/xsd-exp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (~/xsd-exp/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (~/xsd-exp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (~/xsd-exp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (~/xsd-exp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (~/xsd-exp/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Stack:
TypeError: Cannot read property 'id' of undefined
    at ContextBase.copyNamespace (~/xsd-exp/node_modules/cxml/dist/xml/ContextBase.js:33:50)
    at Object.exportNamespace (~/xsd-exp/node_modules/cxsd/dist/xsd/Exporter.js:142:32)
    at ~/xsd-exp/node_modules/cxsd/dist/cli.js:40:35
    at tryCatcher (~/xsd-exp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (~/xsd-exp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (~/xsd-exp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (~/xsd-exp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (~/xsd-exp/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (~/xsd-exp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (~/xsd-exp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (~/xsd-exp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (~/xsd-exp/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by zzynx** [comment]
I found out that adding 'targetNamespace' indeed solves the problem.
However, it does matter **what** you pass as value. (of course ;-))

My problem was gone by adding eg. targetNamespace="urn:myoutput" 
So, my xsd file looks like:

`<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:myoutput" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.0">
      ....
</xs:schema>
`

As output I got (among others) two files: `myoutput.js` and `myoutput.d.ts`
I hope it helps for you guys.

**Comment by ericblade** [comment]
fwiw, adding targetNamespace="urn:whatever" seems to solve the issue for Amazon MWS XSD files.  Unfortunately, there doesn't seem to be a complete archive of those files anywhere to try to run through it, and it just blows up with a ton of 404's.

**Comment by ericblade** [comment]
@moltar i just created a little script that turns the MWS XSD's into ts definitions using cxsd: https://github.com/ericblade/mws-types

**Comment by OnkelTem** [comment]
> However, it does matter **what** you pass as value. (of course ;-))

Sorry, what do you mean what? That what you've added - `urn:myoutput` - did it have some special meaning in your schema?

In other words - it didn't work for me at all.

**Comment by OnkelTem** [comment]
Ok, after beating my head against the wall for a while I now see the idea is dead. No TypeScript, no XML. Bye XSD. You were pretty good. As a matter of fact - the best information declaration tool and the only with sensible types. But people of this planet want to play JSON and YAML crap.

**Comment by saintmatthieu** [comment]
@craigsimko, it works for me with your xsd, cxsd version 0.1.1. I reproduce your problem (with your xsd saved as `test.xsd`) by doing the following :
1. Setup: save your xsd as `test.xsd` in the root and serve the root (e.g., `npx serve`)
2. remove `targetNamespace="http://some/awesome/schema"` from test.xsd,
3. run `npm run cxsd http://localhost:3000/test.xsd`
4. put back `targetNamespace="http://some/awesome/schema"` where it was
5. run `npm run cxsd http://localhost:3000/test.xsd` again

Step 3 makes a copy of test.xsd in a "cache" directory, so that when running 5., it still reads the version without `targetNamespace="http://some/awesome/schema"`. If that's what caused your problem, removing the cache and running again should be your fix.

**Comment by victors1681** [comment]
nothing here works for me.. :(
